// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:airledger/services/sim_fit.dart';
import 'package:googleapis/sheets/v4.dart' as gsheets;
import 'package:googleapis_auth/auth_io.dart';

/// Program-simulation calibration + walk-forward validation study
/// (airledger repo, docs/superpowers/specs/2026-09-25-program-simulation-spec.md, W1).
///
///   dart run tool/sim_calibrate.dart [--out <markdown path>]
///                                    [--fixture <json path>]
///
/// Thin shell (W2 refactor): sheets IO + markdown only. The weekly
/// series, phase detection, block fits, and walk-forward validation all
/// live in lib/services/sim_fit.dart — the SAME code the app's
/// on-demand refit runs. `--fixture` freezes the weekly series as JSON
/// (test/fixtures/sim_weekly_series.json) for the W2 acceptance-gate
/// test, which must reproduce this study's S4/C2 MAE table offline.
///
/// Output is the full markdown study (stdout, and --out writes it) —
/// the source for docs/superpowers/specs/2026-09-25-sim-calibration-study.md.
final home = Platform.environment['HOME']!;
final configPath = '$home/.config/airledger/config.yaml';

Future<void> main(List<String> args) async {
  String? argOf(String flag) {
    final i = args.indexOf(flag);
    return i >= 0 && i + 1 < args.length ? args[i + 1] : null;
  }

  final outPath = argOf('--out');
  final fixturePath = argOf('--fixture');

  final config = readConfig();
  final api = await sheetsApi(config.keyPath);

  Future<List<List<Object?>>> tab(String name) async {
    try {
      final resp = await api.spreadsheets.values.get(
        config.spreadsheetId,
        "'$name'",
      );
      return resp.values ?? [];
    } on gsheets.DetailedApiRequestError catch (e) {
      if (e.status == 400) return [];
      rethrow;
    }
  }

  final strengthTab = await tab('strength');
  final weightTab = await tab('weight');
  final climbTab = await tab('kaya_ascents');

  // -------------------------------------------------------------------------
  // Rows (sim_fit parsing; anomalies counted, not fatal)
  // -------------------------------------------------------------------------
  final anomalies = <String, int>{};
  void anomaly(String kind) => anomalies[kind] = (anomalies[kind] ?? 0) + 1;

  final strengthRows = strengthRowsFromTab(strengthTab, onAnomaly: anomaly);
  final weightRows = weightRowsFromTab(weightTab, onAnomaly: anomaly);
  final climbs = climbsFromTab(climbTab, onAnomaly: anomaly);

  // -------------------------------------------------------------------------
  // Weekly series + phase runs + fit observations (sim_fit)
  // -------------------------------------------------------------------------
  final series = buildWeeklySeries(
    strengthRows: strengthRows,
    weightRows: weightRows,
    climbs: climbs,
  );
  if (fixturePath != null) {
    File(fixturePath).writeAsStringSync(
      const JsonEncoder.withIndent(' ').convert(series.toJson()),
    );
    stderr.writeln('wrote fixture $fixturePath');
  }

  final mondays = series.mondays;
  final n = series.length;
  final bw = series.bw;
  final e1rm = series.e1rm;
  final gradeP75 = series.gradeP75;
  final runs = detectPhaseRuns(series);
  final obs = blockObservations(series, runs);
  final strengthObs = obs.strength;
  final climbObs = obs.climb;
  final levelObs = obs.level;

  final gradedCount = strengthObsGradedCount(strengthRows);

  // -------------------------------------------------------------------------
  // Markdown study
  // -------------------------------------------------------------------------
  final md = StringBuffer();
  void p(String s) => md.writeln(s);

  p('# Sim calibration study — phase response models from full history');
  p('');
  p('Generated by `tool/sim_calibrate.dart` (ledger repo) on '
      '${ymd(DateTime.now())}. Companion to the program-simulation spec '
      '(2026-09-25) and design doc; W2 consumes the coefficients + '
      'validation gates below.');
  p('');
  p('## Inputs');
  p('');
  p('- ${strengthRows.length} strength rows ($gradedCount graded '
      'main-lift sets), ${weightRows.length} weigh-ins, ${climbs.length} '
      'kaya ascents (${climbs.where((c) => c.vGrade != null).length} with '
      'numeric V grades).');
  p('- $n ISO weeks: ${ymd(mondays.first)} .. ${ymd(mondays.last)} '
      '(Monday-keyed, matching coach_backtest; physiology does not care '
      'about the v7 Saturday accounting week).');
  p('- Strength measure: weekly best **RPE-adjusted e1RM** '
      '(`rpeAdjustedE1rm`, reps capped at 12) per lift, carried forward '
      'through untrained weeks. Best actual weight is tabulated for the '
      'state vector but the fits use e1RM (denser, less rep-scheme '
      'aliasing).');
  p('- Climbing measure: rolling 4-week p75 of numeric V grades '
      '(>= 5 ascents per window).');
  if (anomalies.isNotEmpty) {
    p('- Row anomalies (skipped): '
        '${[for (final e in anomalies.entries) '${e.value}x ${e.key}'].join('; ')}.');
  }
  p('');

  // Phase table.
  p('## Detected phase windows (bw trajectory)');
  p('');
  p('Centered smoothed rate, gain >= +0.15 lb/wk, loss <= -0.15, runs '
      '< 4 wk merged into the longer neighbor, run label from net rate '
      '(+/-0.1 lb/wk).');
  p('');
  p('| window | weeks | type | bw start → end | net rate lb/wk |');
  p('|---|---|---|---|---|');
  for (final r in runs) {
    final len = r.end - r.start + 1;
    final b0 = bw[r.start];
    final b1 = bw[r.end];
    final netRate =
        (b0 != null && b1 != null && r.end > r.start)
            ? (b1 - b0) / (r.end - r.start)
            : null;
    p('| ${ymd(mondays[r.start])} .. ${ymd(mondays[r.end])} | $len | '
        '${r.label} | ${fmt(b0)} → ${fmt(b1)} | ${fmt(netRate, 2)} |');
  }
  p('');
  p('Known anchors for corroboration: 2024 bulk ~Apr–Jul 2024; cut after; '
      'bulk Nov 2024 – Oct 2025 with the 2025-02-05 weigh-in trough '
      '(dashboards.yaml `last_bulk` derivation); current cut since '
      '2025-10-06 (coach/phase.yaml).');
  p('');

  // State vector now.
  p('## Current state vector (latest week ${ymd(mondays.last)})');
  p('');
  final last = n - 1;
  p('| quantity | value |');
  p('|---|---|');
  p('| bw 7d mean | ${fmt(bw[last])} lb |');
  for (final l in simLifts) {
    p('| $l e1RM (RPE-adj, carried) | ${fmt(e1rm[l]![last])} lb |');
    p('| $l best actual (carried) | '
        '${fmt(series.bestActual[l]![last])} lb |');
  }
  p('| Wilks (SBD actual-max) | ${fmt(series.wilks[last])} |');
  p('| climb grade p75 (rolling 4wk, carried) | ${fmt(gradeP75[last])} |');
  p('| climb sessions/wk (last 4wk) | '
      '${fmt([for (var i = math.max(0, n - 4); i < n; i++) series.climbSessions[i].toDouble()].fold<double>(0, (a, b) => a + b) / math.min(4, n))} |');
  p('');

  // Descriptive per-phase velocities.
  p('## Per-phase-type mean velocities (descriptive)');
  p('');
  p('Block-level (4-wk) means; the regression below is the model, this '
      'table is the sanity check.');
  p('');
  p('| phase | n blocks | mean bw rate | mean e1RM velocity (all lifts) | '
      'mean heavy sets/wk | n climb blocks | mean grade velocity |');
  p('|---|---|---|---|---|---|---|');
  for (final phase in ['gain', 'loss', 'flat']) {
    final s = [for (final o in strengthObs) if (o.phase == phase) o];
    final c = [for (final o in climbObs) if (o.phase == phase) o];
    p('| $phase | ${s.length} | '
        '${fmt(mean([for (final o in s) o.bwRate]), 2)} | '
        '${fmt(mean([for (final o in s) o.velocity]), 2)} | '
        '${fmt(mean([for (final o in s) o.heavy]), 2)} | ${c.length} | '
        '${fmt(mean([for (final o in c) o.velocity]), 3)} |');
  }
  p('');

  // -------------------------------------------------------------------------
  // Fits (sim_fit ols/fitStats; the tool only formats)
  // -------------------------------------------------------------------------
  p('## Strength response model');
  p('');
  p('OLS over non-overlapping 4-week blocks inside detected phases '
      '(lift trained >= 2 weeks in block and fresh at the endpoint):');
  p('');
  p('    e1rm_velocity[lift] (lb/wk) = a + b_bw * bw_rate (lb/wk) '
      '+ b_hx * near_max_sets_per_wk[lift]');
  p('');
  p('| scope | n | a (intercept) | b_bw | b_hx | R² | MAE lb/wk |');
  p('|---|---|---|---|---|---|---|');

  Map<String, double>? report(String label, List<SimStrengthObs> o) {
    if (o.length < 6) {
      p('| $label | ${o.length} | — | — | — | — | — (insufficient) |');
      return null;
    }
    final X = [
      for (final e in o) [1.0, e.bwRate, e.heavy],
    ];
    final y = [for (final e in o) e.velocity];
    final beta = ols(X, y);
    if (beta == null) {
      p('| $label | ${o.length} | — | — | — | — | — (singular) |');
      return null;
    }
    final f = fitStats(X, y, beta);
    p('| $label | ${o.length} | ${fmt(beta[0], 3)} | ${fmt(beta[1], 3)} | '
        '${fmt(beta[2], 3)} | ${fmt(f.r2, 2)} | ${fmt(f.mae, 2)} |');
    return {'a': beta[0], 'b_bw': beta[1], 'b_hx': beta[2]};
  }

  final pooled = report('pooled (all lifts)', strengthObs);
  for (final l in simLifts) {
    report(l, [for (final o in strengthObs) if (o.lift == l) o]);
  }
  p('');
  if (pooled != null) {
    p('**Headline**: strength velocity responds to bw rate at '
        '**${fmt(pooled['b_bw'], 2)} lb/wk of e1RM per +1 lb/wk of '
        'bodyweight**, intercept ${fmt(pooled['a'], 2)} lb/wk at flat bw '
        'and zero heavy exposure, +${fmt(pooled['b_hx'], 3)} lb/wk per '
        'weekly near-max set.');
  }
  p('');

  // bw-only spec (the collinearity check + the integrable sim candidate).
  p('### bw-only spec (candidate for the sim core)');
  p('');
  p('Same blocks, heavy exposure dropped: '
      '`velocity = a + b_bw * bw_rate`. Near-max exposure in this history '
      'is programmed WITH the phase (bulks lift heavy), so the two-term '
      'model splits shared variance and the b_hx term compounds badly '
      'when integrated over long horizons (see validation). The bw-only '
      'spec keeps the lever the user actually pulls.');
  p('');
  p('| scope | n | a | b_bw | R² | MAE lb/wk |');
  p('|---|---|---|---|---|---|');
  void bwOnly(String label, List<SimStrengthObs> o) {
    if (o.length < 6) {
      p('| $label | ${o.length} | — | — | — | — (insufficient) |');
      return;
    }
    final X = [
      for (final e in o) [1.0, e.bwRate],
    ];
    final y = [for (final e in o) e.velocity];
    final beta = ols(X, y);
    if (beta == null) return;
    final f = fitStats(X, y, beta);
    p('| $label | ${o.length} | ${fmt(beta[0], 3)} | ${fmt(beta[1], 3)} | '
        '${fmt(f.r2, 2)} | ${fmt(f.mae, 2)} |');
  }

  bwOnly('pooled (all lifts)', strengthObs);
  bwOnly('pooled, 2023+ era', [
    for (final o in strengthObs)
      if (!o.start.isBefore(DateTime(2023))) o,
  ]);
  for (final l in simLifts) {
    bwOnly(l, [for (final o in strengthObs) if (o.lift == l) o]);
  }
  p('');

  p('## Climbing response model');
  p('');
  p('    grade_p75_velocity (V/wk) = a + b_f * sessions_per_wk '
      '+ b_bw * bw_rate (lb/wk)');
  p('');
  p('| scope | n | a | b_f | b_bw | R² | MAE V/wk |');
  p('|---|---|---|---|---|---|---|');
  if (climbObs.length >= 6) {
    final X = [
      for (final o in climbObs) [1.0, o.freq, o.bwRate],
    ];
    final y = [for (final o in climbObs) o.velocity];
    final beta = ols(X, y);
    if (beta != null) {
      final f = fitStats(X, y, beta);
      p('| all blocks | ${climbObs.length} | ${fmt(beta[0], 4)} | '
          '${fmt(beta[1], 4)} | ${fmt(beta[2], 4)} | ${fmt(f.r2, 2)} | '
          '${fmt(f.mae, 3)} |');
    }
  } else {
    p('| all blocks | ${climbObs.length} | — | — | — | — | — (insufficient) |');
  }
  p('');

  // Level-anchored climbing spec: grade tracks bw LEVEL (weight is the
  // dominant physical term in bouldering); no integration → no drift.
  p('### level-anchored spec (candidate for the sim core)');
  p('');
  p('    grade_p75 (V) = c0 + c_bw * bw (lb)   — weekly non-carried p75 obs');
  p('');
  p('| n weeks | c0 | c_bw | R² | MAE V |');
  p('|---|---|---|---|---|');
  if (levelObs.length >= 8) {
    final X = [
      for (final o in levelObs) [1.0, o.bwLb],
    ];
    final y = [for (final o in levelObs) o.p75];
    final beta = ols(X, y);
    if (beta != null) {
      final f = fitStats(X, y, beta);
      p('| ${levelObs.length} | ${fmt(beta[0], 2)} | ${fmt(beta[1], 4)} | '
          '${fmt(f.r2, 2)} | ${fmt(f.mae, 2)} |');
    }
  } else {
    p('| ${levelObs.length} | — | — | — | — (insufficient) |');
  }
  p('');

  // -------------------------------------------------------------------------
  // Walk-forward validation (sim_fit.walkForward; the tool only formats)
  // -------------------------------------------------------------------------
  p('## Walk-forward validation');
  p('');
  p('For each held-out window every model variant is REFIT on blocks '
      'strictly before the window start, then integrated weekly from the '
      'window-start observed state using OBSERVED weekly inputs (3-wk '
      'trailing bw rate; the week\'s near-max sets; climb sessions). '
      'Baseline = flat at the window-start value. MAE over weeks with a '
      'fresh (non-carried) observation.');
  p('');
  p('Strength variants: **S1** pooled `a + b_bw·rate + b_hx·heavy`; '
      '**S2** pooled `a + b_bw·rate`; **S3** per-lift `a + b_bw·rate` '
      '(pooled fallback when the lift has < 20 prior blocks); '
      '**S4** = S3 with positive velocities dampened by proximity to the '
      'lift\'s pre-window all-time e1RM peak (linear fade from full at '
      '95% of peak to zero at 105% — the training-age/saturation rule). '
      'Climbing variants: **C1** velocity `a + b_f·freq + b_bw·rate` '
      'integrated; **C2** level-anchored `p75 = c0 + c_bw·bw` evaluated '
      'at observed weekly bw. Wilks row: S4 SBD e1RM deltas applied to '
      'the window-start actual-max total, scored at observed bw '
      '(approximate — basis mismatch is a caveat, not a bug).');
  p('');

  final windows = defaultValidationWindows(series);
  final wf = walkForward(series, windows: windows);

  p('| window | output | flat | S1 bw+hx | S2 bw | S3 per-lift bw | '
      'S4 S3+saturation | best |');
  p('|---|---|---|---|---|---|---|---|');
  for (final win in windows) {
    final winRows = [for (final r in wf.rows) if (r.window == win.name) r];
    final prior = [
      for (final d in wf.priorData)
        if (d.window == win.name) d,
    ];
    if (prior.isEmpty) {
      p('| ${win.name} | — | no weeks in range | | | | |');
      continue;
    }
    for (final r in winRows) {
      if (r.output.endsWith('e1RM (lb)')) {
        p('| ${r.window} | ${r.output} | ${fmt(r.flat, 1)} | '
            '${fmt(r.models['S1'], 1)} | ${fmt(r.models['S2'], 1)} | '
            '${fmt(r.models['S3'], 1)} | ${fmt(r.models['S4'], 1)} | '
            '${r.best} |');
      } else if (r.output == 'Wilks (derived, S4)') {
        p('| ${r.window} | ${r.output} | ${fmt(r.flat, 1)} | | | | '
            '${fmt(r.models['S4'], 1)} | ${r.best} |');
      } else if (r.output == 'climb grade p75 (V)') {
        p('| ${r.window} | ${r.output} | ${fmt(r.flat, 2)} | '
            'C1: ${fmt(r.models['C1'], 2)} | C2: ${fmt(r.models['C2'], 2)} | '
            '| | ${r.best} |');
      }
    }
    final d = prior.first;
    p('| ${win.name} | _prior data_ | _${d.strengthBlocks} strength blocks, '
        '${d.climbBlocks} climb blocks, ${d.levelWeeks} climb level weeks_ '
        '| | | | | |');
  }
  p('');

  p('## Verdict — model selection for the W2 sim core');
  p('');
  p('- **Strength: S4** (per-lift `a + b_bw·rate`, positive velocity '
      'dampened linearly to zero as e1RM runs from 95% to 105% of the '
      'all-time peak). Best or near-best on the 2024 bulk and the '
      'current cut, and the closest model to flat on the anomalous 2025 '
      'bulk; never materially worse than S3. S1 (heavy-exposure term) '
      'is rejected for the sim core: the b_hx term compounds '
      'catastrophically over long horizons (2025 bulk squat MAE 56 vs '
      'flat 24).');
  p('- **Climbing: C2** (level-anchored `p75 = c0 + c_bw·bw`). The '
      'integrated velocity model (C1) drifts unboundedly; the level '
      'model cannot drift and beat flat on the current cut. Session '
      'frequency stays a lever via the C1 b_f term surfaced in the UI, '
      'but the forecast line comes from C2.');
  p('- **Wilks**: derived output — wilks(SBD total from simulated '
      'e1RMs, simulated bw); no separate model.');
  p('- **W2 acceptance gate**: reproduce this study\'s S4 + C2 MAE '
      'table from the same frozen inputs (pure-Dart sim core, no '
      'network) to within 0.1; the design doc carries the numbers.');
  p('');

  p('## Caveats (honest)');
  p('');
  p('- **The 2025 bulk is a known anomaly, not just model error**: the '
      'coach backtest documents a mid-bulk training collapse '
      '(NEAR_MAX_LOW + LONG_SETS flags May–Jun 2025; weekly working '
      'sets fell from ~24 to ~14). Every model overshoots a bulk whose '
      'inputs collapsed; the sim treats planned inputs as delivered.');
  p('- **Current-cut deadlift MAEs (~90–120 lb) are a regime change**: '
      'the deadlift carries a pain cap (working_max seed marker) and '
      'its e1RM collapsed for reasons outside the bw-rate model. '
      'Injury is not simulable; the nightly refit re-anchors the sim '
      'to the post-injury state instead.');
  p('- **Heavy-exposure collinearity**: near-max exposure and bw rate '
      'move together (bulks program heavier work); b_bw and b_hx split '
      'shared variance and their individual values are less stable than '
      'the joint prediction. The sim should treat the PREDICTION as '
      'calibrated, not each coefficient separately.');
  p('- **Era effects**: earlier phases are also earlier training age; '
      'some of the bulk-phase velocity is newbie-adjacent gains the next '
      'bulk will not reproduce. Walk-forward validation partially prices '
      'this in (it always predicts forward), but the long-horizon sim '
      'inherits optimism. Nightly refit shrinks this as recent data '
      'accumulates.');
  p('- **Carried e1RM weeks are skipped in scoring** (untrained weeks '
      'have no fresh observation); MAEs are over trained weeks only.');
  p('- **Climbing p75 is volume-sensitive**: p75 of attempted grades '
      'confounds ability with session intent (limit vs volume days); '
      'blocks need >= 5 graded ascents and the series is still noisy.');
  p('- **RPE sparsity**: rpeAdjustedE1rm falls back to raw Epley when '
      'RPE is not logged; older eras logged RPE less.');
  p('- **Wilks validation is derived**, not an independent fit: e1RM '
      'deltas applied to an actual-max total (basis mismatch noted '
      'above).');

  final out = md.toString();
  print(out);
  if (outPath != null) {
    File(outPath).writeAsStringSync(out);
    stderr.writeln('\nwrote $outPath');
  }
}

// ---------------------------------------------------------------------------
// Config / API (coach_backtest.dart pattern)
// ---------------------------------------------------------------------------

({String spreadsheetId, String keyPath}) readConfig() {
  final lines = File(configPath).readAsLinesSync();
  String? pick(String key) {
    for (final l in lines) {
      if (l.startsWith('$key:')) return l.substring(key.length + 1).trim();
    }
    return null;
  }

  final spreadsheetId = pick('spreadsheet_id');
  if (spreadsheetId == null || spreadsheetId.isEmpty) {
    print('no spreadsheet_id in $configPath');
    exit(1);
  }
  final keyPath =
      pick('service_account_key_path') ??
      '$home/.config/airledger/service-account.json';
  return (spreadsheetId: spreadsheetId, keyPath: keyPath);
}

Future<gsheets.SheetsApi> sheetsApi(String keyPath) async {
  final keyJson = await File(keyPath).readAsString();
  final credentials = ServiceAccountCredentials.fromJson(keyJson);
  final client = await clientViaServiceAccount(credentials, [
    gsheets.SheetsApi.spreadsheetsScope,
  ]);
  return gsheets.SheetsApi(client);
}

String ymd(DateTime d) =>
    '${d.year}-${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

String fmt(double? v, [int dp = 1]) => v == null ? '—' : v.toStringAsFixed(dp);
